# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-24 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('isbn', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='lists.Books')),
                ('nz_dollars', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='NZ$')),
                ('us_dollars', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='US$')),
                ('uk_pounds', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='UK£')),
            ],
        ),
    ]
