# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-26 21:46
from __future__ import unicode_literals

from django.conf import settings  # type: ignore
from django.db import migrations, models  # type: ignore
import django.db.models.deletion  # type: ignore
import lists.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lists', '0002_auto_20161226_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('currency', models.CharField(max_length=1000)),
                ('spend', models.DecimalField(decimal_places=2, max_digits=12)),
                ('day_of_month', models.IntegerField(validators=[lists.models._validate_day_of_month])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WishLists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lists.Lists')),
            ],
        ),
    ]
