# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-07 03:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_lists_wishlists'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': 'book', 'verbose_name_plural': 'books'},
        ),
        migrations.AlterModelOptions(
            name='lists',
            options={'verbose_name': 'list', 'verbose_name_plural': 'lists'},
        ),
        migrations.AlterModelOptions(
            name='prices',
            options={'verbose_name': 'price', 'verbose_name_plural': 'prices'},
        ),
        migrations.AlterModelOptions(
            name='wishlists',
            options={'verbose_name': 'wish list', 'verbose_name_plural': 'wish lists'},
        ),
        migrations.AddField(
            model_name='books',
            name='series',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='series_order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wishlists',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to='lists.Lists'),
        ),
    ]
